#!/usr/bin/env python3
"""
Comprehensive Environment Setup for ATS System
Creates .env files for both backend and server with all required variables
"""

import os
import sys
from pathlib import Path
import getpass

def create_env_file(file_path: Path, variables: dict, existing_content: str = ""):
    """Create or update .env file with variables"""
    
    # Parse existing content to preserve any existing variables
    existing_vars = {}
    if existing_content:
        for line in existing_content.split('\n'):
            line = line.strip()
            if line and '=' in line and not line.startswith('#'):
                key, value = line.split('=', 1)
                existing_vars[key.strip()] = value.strip()
    
    # Merge with new variables (existing take precedence)
    final_vars = {**variables, **existing_vars}
    
    # Create content
    content = "# ATS System Environment Variables\n"
    content += "# Generated by setup_environment.py\n\n"
    
    for key, value in final_vars.items():
        content += f"{key}={value}\n"
    
    # Write file
    with open(file_path, 'w') as f:
        f.write(content)
    
    print(f"✅ Created/updated {file_path}")

def get_user_input(prompt: str, default: str = "", is_password: bool = False) -> str:
    """Get user input with optional default value"""
    if default:
        prompt += f" (default: {default}): "
    else:
        prompt += ": "
    
    if is_password:
        value = getpass.getpass(prompt)
    else:
        value = input(prompt)
    
    return value if value else default

def main():
    print("🚀 ATS System Environment Setup")
    print("=" * 50)
    
    base_dir = Path(__file__).parent
    
    # Check for existing .env files
    backend_env = base_dir / "backend" / ".env"
    server_env = base_dir / "server" / ".env"
    
    existing_backend = ""
    existing_server = ""
    
    if backend_env.exists():
        with open(backend_env, 'r') as f:
            existing_backend = f.read()
        print("📁 Found existing backend/.env file")
    
    if server_env.exists():
        with open(server_env, 'r') as f:
            existing_server = f.read()
        print("📁 Found existing server/.env file")
    
    print("\n🔧 Setting up environment variables...")
    
    # Backend environment variables
    print("\n📋 Backend Environment Variables:")
    print("-" * 30)
    
    backend_vars = {}
    
    # Hugging Face API Token
    hf_token = get_user_input(
        "Enter your Hugging Face API Token",
        default="hf_your_token_here"
    )
    backend_vars["HUGGINGFACE_API_TOKEN"] = hf_token
    
    # MongoDB URI
    mongo_uri = get_user_input(
        "Enter MongoDB connection URI",
        default="mongodb://localhost:27017/ats_db"
    )
    backend_vars["MONGODB_URI"] = mongo_uri
    
    # Optional: Add other backend variables
    backend_vars["LOG_LEVEL"] = "INFO"
    backend_vars["UPLOAD_DIR"] = "uploads"
    
    # Server environment variables
    print("\n📋 Server Environment Variables:")
    print("-" * 30)
    
    server_vars = {}
    
    # MongoDB URI (same as backend)
    server_vars["MONGO_URI"] = mongo_uri
    
    # JWT Secret
    jwt_secret = get_user_input(
        "Enter JWT secret key",
        default="your-super-secret-jwt-key-change-this-in-production"
    )
    server_vars["JWT_SECRET"] = jwt_secret
    
    # Email configuration
    email_user = get_user_input(
        "Enter email address for notifications",
        default="your-email@gmail.com"
    )
    server_vars["EMAIL_USER"] = email_user
    
    email_pass = get_user_input(
        "Enter email password/app password",
        default="your-email-password",
        is_password=True
    )
    server_vars["EMAIL_PASS"] = email_pass
    
    # Optional: Add other server variables
    server_vars["PORT"] = "5000"
    server_vars["NODE_ENV"] = "development"
    
    # Create/update .env files
    print("\n📝 Creating environment files...")
    
    # Ensure directories exist
    (base_dir / "backend").mkdir(exist_ok=True)
    (base_dir / "server").mkdir(exist_ok=True)
    
    # Create backend .env
    create_env_file(backend_env, backend_vars, existing_backend)
    
    # Create server .env
    create_env_file(server_env, server_vars, existing_server)
    
    print("\n✅ Environment setup complete!")
    print("\n📋 Summary:")
    print(f"  Backend .env: {backend_env}")
    print(f"  Server .env: {server_env}")
    
    print("\n🔒 Security Notes:")
    print("  - Keep your .env files secure and never commit them to version control")
    print("  - Change default passwords and secrets in production")
    print("  - Use strong JWT secrets in production")
    
    print("\n🚀 Next Steps:")
    print("  1. Install dependencies: npm install (in server/ and client/)")
    print("  2. Install Python packages: pip install -r requirements.txt (in backend/)")
    print("  3. Start the services using: ./start_backends.ps1")
    
    return True

if __name__ == "__main__":
    try:
        success = main()
        sys.exit(0 if success else 1)
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Error during setup: {e}")
        sys.exit(1) 